#!/usr/bin/env python3
"""
Architecture definition for Prunnerai test v.1.0
Generated by Priority Living Labs Model Forge

Architecture: moe
Target size:  3B parameters
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class RMSNorm(nn.Module):
    def __init__(self, dim, eps=1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x):
        norm = x.float().pow(2).mean(-1, keepdim=True).add(self.eps).rsqrt()
        return (x * norm).type_as(x) * self.weight


class Expert(nn.Module):
    def __init__(self, dim, hidden_dim):
        super().__init__()
        self.w1 = nn.Linear(dim, hidden_dim, bias=False)
        self.w2 = nn.Linear(hidden_dim, dim, bias=False)
        self.w3 = nn.Linear(dim, hidden_dim, bias=False)

    def forward(self, x):
        return self.w2(F.silu(self.w1(x)) * self.w3(x))


class TopKRouter(nn.Module):
    def __init__(self, dim, n_experts, top_k=2):
        super().__init__()
        self.gate = nn.Linear(dim, n_experts, bias=False)
        self.top_k = top_k

    def forward(self, x):
        logits = self.gate(x)
        topk_vals, topk_idx = torch.topk(logits, self.top_k, dim=-1)
        weights = F.softmax(topk_vals, dim=-1)
        return weights, topk_idx


class MoELayer(nn.Module):
    def __init__(self, dim, n_experts=8, top_k=2, hidden_dim=None):
        super().__init__()
        hidden = hidden_dim or dim * 4
        self.experts = nn.ModuleList([Expert(dim, hidden) for _ in range(n_experts)])
        self.router = TopKRouter(dim, n_experts, top_k)
        self.top_k = top_k

    def forward(self, x):
        B, L, D = x.shape
        weights, indices = self.router(x)
        out = torch.zeros_like(x)
        x_flat = x.view(-1, D)
        out_flat = out.view(-1, D)
        for k in range(self.top_k):
            idx = indices[:, :, k].view(-1)
            w = weights[:, :, k].view(-1, 1)
            for e_idx in range(len(self.experts)):
                mask = (idx == e_idx)
                if mask.any():
                    out_flat[mask] += w[mask] * self.experts[e_idx](x_flat[mask])
        return out.view(B, L, D)


class MoEBlock(nn.Module):
    def __init__(self, dim, n_heads, n_experts=8, top_k=2):
        super().__init__()
        from src.model import RMSNorm  # self-reference
        self.attn_norm = RMSNorm(dim)
        self.ffn_norm = RMSNorm(dim)
        head_dim = dim // n_heads
        self.wq = nn.Linear(dim, dim, bias=False)
        self.wk = nn.Linear(dim, dim, bias=False)
        self.wv = nn.Linear(dim, dim, bias=False)
        self.wo = nn.Linear(dim, dim, bias=False)
        self.n_heads = n_heads
        self.head_dim = head_dim
        self.moe = MoELayer(dim, n_experts, top_k)

    def forward(self, x):
        B, L, _ = x.shape
        h = self.attn_norm(x)
        q = self.wq(h).view(B, L, self.n_heads, self.head_dim).transpose(1, 2)
        k = self.wk(h).view(B, L, self.n_heads, self.head_dim).transpose(1, 2)
        v = self.wv(h).view(B, L, self.n_heads, self.head_dim).transpose(1, 2)
        attn = F.scaled_dot_product_attention(q, k, v, is_causal=True)
        attn = attn.transpose(1, 2).contiguous().view(B, L, -1)
        x = x + self.wo(attn)
        x = x + self.moe(self.ffn_norm(x))
        return x


class MoEModel(nn.Module):
    """
    Mixture-of-Experts Transformer.
    Sparse routing activates top-k experts per token.
    """
    def __init__(self, vocab_size=32000, dim=4096, n_layers=32, n_heads=32, n_experts=8, top_k=2):
        super().__init__()
        self.tok_embeddings = nn.Embedding(vocab_size, dim)
        self.layers = nn.ModuleList([MoEBlock(dim, n_heads, n_experts, top_k) for _ in range(n_layers)])
        self.norm = RMSNorm(dim)
        self.output = nn.Linear(dim, vocab_size, bias=False)

    def forward(self, tokens):
        x = self.tok_embeddings(tokens)
        for layer in self.layers:
            x = layer(x)
        return self.output(self.norm(x))


def build_model(**kwargs):
    return MoEModel(**kwargs)
