#!/usr/bin/env python3
"""
Training script for Prunnerai test v.1.0
Generated by Priority Living Labs Model Forge

Framework:  unsloth
Algorithms: lora
"""

import json
import os
import argparse

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "Prunnerai test v.1.0", "config.json")

def load_config():
    with open(CONFIG_PATH) as f:
        return json.load(f)


def train(config):
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    from src.dataset import load_dataset

    # Load or initialize model
    base = config.get("scratch", {}).get("base_model_id") or "unsloth/llama-3-8b-bnb-4bit"
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=base,
        max_seq_length=config.get("context_window", 8192),
        load_in_4bit=True,
    )

    # Apply LoRA
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=32,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    dataset = load_dataset("data/")

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        args=TrainingArguments(
            per_device_train_batch_size=4,
            gradient_accumulation_steps=4,
            warmup_steps=10,
            num_train_epochs=3,
            learning_rate=2e-4,
            fp16=True,
            logging_steps=10,
            output_dir="checkpoints/",
            save_strategy="epoch",
        ),
        max_seq_length=config.get("context_window", 8192),
    )

    trainer.train()
    model.save_pretrained("checkpoints/final")
    tokenizer.save_pretrained("checkpoints/final")
    print("✅ Training complete — checkpoints saved to checkpoints/final")


if __name__ == "__main__":
    config = load_config()
    train(config)
