#!/usr/bin/env python3
"""
Inference script for Prunnerai V.1.0
Generated by Priority Living Labs Model Forge

Supports: vLLM, Ollama, and Transformers backends
"""

import argparse
import json
import os

MODEL_NAME = "Prunnerai V.1.0"
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "models", MODEL_NAME, "config.json")
QUANTIZATION = "q4_k_m"


def load_config():
    """Load model configuration from config.json"""
    with open(CONFIG_PATH) as f:
        return json.load(f)


def run_vllm(prompt: str, config: dict):
    """Run inference using vLLM"""
    try:
        from vllm import LLM, SamplingParams
    except ImportError:
        print("Install vLLM: pip install vllm")
        return

    source = config.get("source_url", MODEL_NAME)
    sampling = SamplingParams(temperature=0.7, max_tokens=4096)
    llm = LLM(model=source, quantization=QUANTIZATION if QUANTIZATION != "fp16" else None)
    outputs = llm.generate([prompt], sampling)
    for output in outputs:
        print(output.outputs[0].text)


def run_ollama(prompt: str, config: dict):
    """Run inference using Ollama"""
    try:
        import requests
    except ImportError:
        print("Install requests: pip install requests")
        return

    system_prompt = config.get("system_prompt", "")
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={"model": MODEL_NAME, "prompt": prompt, "system": system_prompt, "stream": False},
    )
    print(response.json().get("response", ""))


def run_transformers(prompt: str, config: dict):
    """Run inference using HuggingFace Transformers"""
    try:
        from transformers import AutoTokenizer, AutoModelForCausalLM
    except ImportError:
        print("Install transformers: pip install transformers torch")
        return

    source = config.get("source_url", MODEL_NAME)
    tokenizer = AutoTokenizer.from_pretrained(source)
    model = AutoModelForCausalLM.from_pretrained(source)
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(**inputs, max_new_tokens=4096)
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=f"Run inference for {MODEL_NAME}")
    parser.add_argument("--backend", choices=["vllm", "ollama", "transformers"], default="ollama")
    parser.add_argument("--prompt", type=str, default="Hello, how are you?")
    args = parser.parse_args()

    config = load_config()
    backends = {"vllm": run_vllm, "ollama": run_ollama, "transformers": run_transformers}
    backends[args.backend](args.prompt, config)
